# Generated by Django 4.2.7 on 2024-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict_meeting_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('meeting_duration', models.DurationField()),
            ],
        ),
    ]
