# Generated by Django 5.0.4 on 2024-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pict_meeting_calendar', '0002_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': [('can_add_meeting', 'Can add meeting'), ('can_change_meeting', 'Can change meeting'), ('can_delete_meeting', 'Can delete meeting')]},
        ),
    ]
