# Generated by Django 5.0.4 on 2024-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pict_meeting_calendar', '0003_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
    ]
