# Generated by Django 5.0.4 on 2024-04-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pict_meeting_calendar', '0004_alter_meeting_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meeting',
        ),
    ]
